# Site variables
title:       <site title>
description: <site description>

url:       '<site url>'
baseUrl:   '/<site baseUrl>'
pluginUrl: 'https://weitungchen.com/plugins'

# Build settings
markdown: kramdown
theme:    minima
