# Site variables
title:       <site title>
description: <site description>

url:         '<site url>' # remote url  (github/website url)
# url:         'localhost:4000' # local url

baseUrl:     '/<site baseUrl>' # local baseUrl (github repo name)
# baseUrl:     '' # local baseUrl

# Build settings
markdown: kramdown
theme:    minima
